language: bash
services:
  - docker
before_install:
  - bash scripts/install-aws-cli.sh
  - bash scripts/login-to-ecr.sh
script:
  - bash scripts/build-and-push-image.sh
  - bash scripts/create-ec2-instance.sh
  - bash scripts/wait-for-ec2-instance.sh
  - bash scripts/deploy-to-ec2.sh