
language: bash

services:
  - docker

before_install:
  - pip install --upgrade pip
  - pip install awscli
  - aws configure set region us-east-2
  - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
  - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
  - aws configure set default.region $AWS_DEFAULT_REGION
  - aws configure set default.output json

env:
  global:
  - EB_REGION="us-east-2"
  - secure: secure_AWS_ACCOUNT_ID
  - secure: secure_AWS_ACCESS_KEY_ID
  - secure: secure_AWS_SECRET_ACCESS_KEY

script:
  - bash travispull.sh