language: python

services:
  - docker

before_install:
  - pip install awscli

install:
  - docker build -t bfostertesting .dockerfile .

before_script:
  - $(aws ecr get-login --region us-east-2)

script:
  - docker tag 20221230155505-a9bb04859d25c483d39afee2e24a02bebed3ff6a:latest 647269089792.dkr.ecr.us-east-1.amazonaws.com/bftesting:latest
  - docker push 647269089792.dkr.ecr.us-east-1.amazonaws.com/bftesting:latest